# Generated by Django 5.2.4 on 2025-11-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='featured',
            field=models.BooleanField(default=False, help_text='Check to feature this car on the homepage.'),
        ),
    ]
