# Generated by Django 5.2.4 on 2025-12-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sold_out',
            field=models.BooleanField(default=False, help_text='Check to feature this car on the homepage.'),
        ),
    ]
