# Generated by Django 5.2.4 on 2025-12-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='car',
            name='features',
        ),
    ]
