# Generated by Django 5.2.4 on 2025-12-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_sold_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='sold_out',
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('auction', 'Hərrac maşınları'), ('korea_stock', 'Koreya stokumuz'), ('on_the_way', 'Yolda satılır'), ('sold_out', 'Satıldı')], default='korea_stock', max_length=20),
        ),
    ]
