# Generated by Django 5.2.4 on 2025-12-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_sold_out_alter_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='changed_parts_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of parts replaced on the vehicle'),
        ),
        migrations.AddField(
            model_name='car',
            name='painted_parts_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of body parts that have been repainted'),
        ),
    ]
