# Generated by Django 5.2.4 on 2025-12-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_changed_parts_count_car_painted_parts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='paint_test_video_url',
            field=models.CharField(blank=True, help_text="YouTube Link for the car's Paint Test Video", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='promotion_video_url',
            field=models.CharField(blank=True, help_text="YouTube Link for the car's Promotional Video", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Benzin'), ('diesel', 'Dizel'), ('hybrid', 'Hibrid'), ('electric', 'Elektrik')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Avtomatik'), ('manual', 'Mexanika')], max_length=20),
        ),
    ]
