# Generated by Django 5.2.4 on 2025-12-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_paint_test_video_url_car_promotion_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='customs_tax_estimate',
            field=models.IntegerField(help_text='Estimated customs tax for the car (in USD).', null=True),
        ),
    ]
