# Generated by Django 5.2.4 on 2025-12-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_customs_tax_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='customs_tax_estimate',
            field=models.DecimalField(decimal_places=2, help_text='Estimated customs tax for the car (in USD).', max_digits=10, null=True),
        ),
    ]
