# Generated by Django 5.2.4 on 2025-12-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_customs_tax_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
