# Generated by Django 5.2.4 on 2025-12-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Korean Quality, On Baku Roads.', max_length=150, verbose_name='Hero Title')),
                ('hero_subtitle', models.CharField(default='Your reliable, transparent, and fast car supply platform.', max_length=255, verbose_name='Hero Subtitle')),
                ('mission_title', models.CharField(default='Connecting the Markets', max_length=100, verbose_name='Mission Title')),
                ('mission_text_primary', models.TextField(help_text='The first paragraph. Mention the name of the platform.', verbose_name='Mission Text 1 (Primary)')),
                ('mission_text_secondary', models.TextField(help_text='The second paragraph. Detail the selection and delivery process.', verbose_name='Mission Text 2 (Secondary)')),
                ('cta_title', models.CharField(default='Start Your Journey with Confidence.', max_length=100, verbose_name='CTA Title')),
                ('cta_text', models.CharField(default='Have questions about importing your dream car from Korea? Contact our team.', max_length=255, verbose_name='CTA Text')),
            ],
            options={
                'verbose_name': 'About Page Core Data',
                'verbose_name_plural': 'About Page Core Data',
            },
        ),
        migrations.CreateModel(
            name='OurValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Value Title')),
                ('description', models.TextField(max_length=300, verbose_name='Short Description')),
                ('icon_name', models.CharField(help_text='Example: bi-journal-check, bi-tools, bi-truck', max_length=50, verbose_name='Bootstrap Icon Name')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='The order in which the value appears on the page', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Our Value',
                'verbose_name_plural': 'What Makes Us Different (Values)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(unique=True, verbose_name='Step Number')),
                ('tab_label', models.CharField(help_text='E.g., Selection, Transport, Handover', max_length=50, verbose_name='Tab Label (Small)')),
                ('step_title', models.CharField(max_length=100, verbose_name='Step Title (Large)')),
                ('step_description', models.TextField(help_text='Detailed text appearing inside the tab.', verbose_name='Step Description')),
            ],
            options={
                'verbose_name': 'Work Process Step',
                'verbose_name_plural': 'Work Process Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_negotiable',
        ),
    ]
