# Generated by Django 5.2.4 on 2025-12-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_aboutpage_ourvalue_workprocessstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourvalue',
            name='icon_color',
            field=models.CharField(default='info', help_text='Example: info, danger, sucess', max_length=100, verbose_name='Icon color'),
            preserve_default=False,
        ),
    ]
