# Generated by Django 5.2.4 on 2025-12-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_ourvalue_icon_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Automatic Climate Control, Cruise Control', max_length=100, unique=True, verbose_name='Feature Name')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_title',
            field=models.CharField(default=15, help_text='Example: Toyota Camry 2020 • Sedan • 2.5L', max_length=120, null=True, verbose_name='Car Title'),
        ),
        migrations.AddField(
            model_name='car',
            name='first_registration_date',
            field=models.DateField(blank=True, help_text='Leave empty if the first registration date is unknown', null=True, verbose_name='First Registration Date'),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacture_date',
            field=models.DateField(blank=True, help_text='Leave empty if the manufacture date is unknown', null=True, verbose_name='Manufacture Date'),
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(help_text='17-character Vehicle Identification Number', max_length=17, null=True, unique=True, verbose_name='VIN'),
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars', to='cars.carfeature', verbose_name='Features'),
        ),
    ]
