# Generated by Django 5.2.4 on 2025-12-13 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_carfeature_car_car_title_car_first_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_title',
            field=models.CharField(help_text='Example: Toyota Camry 2020 • Sedan • 2.5L', max_length=120, null=True, verbose_name='Car Title'),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='cars', to='cars.carfeature', verbose_name='Features'),
        ),
        migrations.CreateModel(
            name='ChangedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Front Bumper, Rear Door', max_length=100, verbose_name='Part Name')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_parts', to='cars.car')),
            ],
            options={
                'verbose_name': 'Changed Part',
                'verbose_name_plural': 'Changed Parts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PaintedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Hood, Left Door', max_length=100, verbose_name='Part Name')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painted_parts', to='cars.car')),
            ],
            options={
                'verbose_name': 'Painted Part',
                'verbose_name_plural': 'Painted Parts',
                'ordering': ('name',),
            },
        ),
    ]
