# Generated by Django 5.2.4 on 2025-12-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_car_car_title_alter_car_features_changedpart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='changed_parts_count',
        ),
        migrations.RemoveField(
            model_name='car',
            name='first_registration_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='painted_parts_count',
        ),
    ]
