# Generated by Django 5.2.4 on 2025-12-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_remove_car_changed_parts_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_map',
            field=models.ImageField(null=True, upload_to='body_maps/'),
        ),
    ]
