# Generated by Django 5.2.4 on 2025-12-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_car_body_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='customs_tax_estimate',
            field=models.DecimalField(decimal_places=2, help_text='Estimated customs tax for the car.', max_digits=10, null=True),
        ),
    ]
