# Generated by Django 5.2.4 on 2025-12-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_car_customs_tax_estimate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='body_map',
            new_name='damage_map',
        ),
        migrations.AddField(
            model_name='car',
            name='paint_map',
            field=models.ImageField(null=True, upload_to='body_maps/'),
        ),
    ]
