# Generated by Django 5.2.4 on 2025-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_rename_body_map_car_damage_map_car_paint_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='changed_parts_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='painted_parts_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
