# Generated by Django 5.2.4 on 2025-11-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_featured'),
        ('orders', '0001_initial'),
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='object_id',
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car'),
        ),
        migrations.AddField(
            model_name='order',
            name='spare_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spareparts.sparepart'),
        ),
    ]
